spring:
  application:
    name: sbc-permission

  profiles:
    active: local

server:
  host: localhost
  port: 7011
  servlet:
    session:
      timeout: 3600s

eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:7002/eureka/ #47.104.240.104

mybatis:
  typeAliasesPackage: cn.wzl.sbc.model
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    cn.wzl.sbc: debug  #mybatis输出sql日志
