spring:
  application:
    #该项目名
    name: sbc-chatboard
  profiles:
    active: local

#eureka服务器端口号7001开始算，业务逻辑模块端口号7011开始计算，其他插件模块端口号7021开始计算
server:
  host: localhost
  port: 7012

  servlet:
    session:
      timeout: 3600s

eureka:
  client:
    #此项目作为客户端注册
    register-with-eureka: true #是否需要注册
    service-url:
      defaultZone: http://root:root@localhost:7002/eureka #47.104.240.104

mybatis:
  typeAliasesPackage: cn.wzl.sbc.model
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true



#日志输出级别
logging:
  level:
    cn.wzl.sbc: debug  #mybatis输出sql日志
