spring:
  application:
    name: sbc-eureka #该项目名
  #开启权限认证
  security:
    basic:
      enabled: true
    user:
      name: root
      password: root
server:
  host: localhost
  port: 7002

eureka:
  client:
    #此项目不作为客户端注册
    register-with-eureka: false #是否需要注册
    fetch-registry: false #是否需要检索
